/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using humorapi.Model;
using humorapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace humorapi.Test.Model
{
    /// <summary>
    ///  Class for testing RateWord200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RateWord200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RateWord200Response
        //private RateWord200Response instance;

        public RateWord200ResponseTests()
        {
            // TODO uncomment below to create an instance of RateWord200Response
            //instance = new RateWord200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RateWord200Response
        /// </summary>
        [Fact]
        public void RateWord200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RateWord200Response
            //Assert.IsType<RateWord200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
    }
}
