/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using humorapi.Model;
using humorapi.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace humorapi.Test.Model
{
    /// <summary>
    ///  Class for testing SearchGifs200ResponseImagesInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchGifs200ResponseImagesInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchGifs200ResponseImagesInner
        //private SearchGifs200ResponseImagesInner instance;

        public SearchGifs200ResponseImagesInnerTests()
        {
            // TODO uncomment below to create an instance of SearchGifs200ResponseImagesInner
            //instance = new SearchGifs200ResponseImagesInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchGifs200ResponseImagesInner
        /// </summary>
        [Fact]
        public void SearchGifs200ResponseImagesInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchGifs200ResponseImagesInner
            //Assert.IsType<SearchGifs200ResponseImagesInner>(instance);
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Fact]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Fact]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
    }
}
