/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.SearchMemes200ResponseMemesInner;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * 
 **/
@ApiModel(description = "")
public class SearchMemes200Response {
  
  @SerializedName("memes")
  private Set<SearchMemes200ResponseMemesInner> memes = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Set<SearchMemes200ResponseMemesInner> getMemes() {
    return memes;
  }
  public void setMemes(Set<SearchMemes200ResponseMemesInner> memes) {
    this.memes = memes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchMemes200Response searchMemes200Response = (SearchMemes200Response) o;
    return (this.memes == null ? searchMemes200Response.memes == null : this.memes.equals(searchMemes200Response.memes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.memes == null ? 0: this.memes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchMemes200Response {\n");
    
    sb.append("  memes: ").append(memes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
