# coding: utf-8

"""
    Humor API

    Awesome Humor API.

    The version of the OpenAPI document: 1.0
    Contact: mail@humorapi.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from humorapi.models.search_gifs200_response_images_inner import SearchGifs200ResponseImagesInner

class TestSearchGifs200ResponseImagesInner(unittest.TestCase):
    """SearchGifs200ResponseImagesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchGifs200ResponseImagesInner:
        """Test SearchGifs200ResponseImagesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchGifs200ResponseImagesInner`
        """
        model = SearchGifs200ResponseImagesInner()
        if include_optional:
            return SearchGifs200ResponseImagesInner(
                url = '0',
                width = 56,
                height = 56
            )
        else:
            return SearchGifs200ResponseImagesInner(
                url = '0',
                width = 56,
                height = 56,
        )
        """

    def testSearchGifs200ResponseImagesInner(self):
        """Test SearchGifs200ResponseImagesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
