=begin comment

Humor API

Awesome Humor API.

The version of the OpenAPI document: 1.0
Contact: mail@humorapi.com
Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::MemesApi');

my $api = WWW::OpenAPIClient::MemesApi->new();
isa_ok($api, 'WWW::OpenAPIClient::MemesApi');

#
# downvote_meme test
#
# uncomment below and update the test
#my $downvote_meme_id = undef; # replace NULL with a proper value
#my $downvote_meme_result = $api->downvote_meme(id => $downvote_meme_id);

#
# random_meme test
#
# uncomment below and update the test
#my $random_meme_keywords = undef; # replace NULL with a proper value
#my $random_meme_keywords_in_image = undef; # replace NULL with a proper value
#my $random_meme_media_type = undef; # replace NULL with a proper value
#my $random_meme_number = undef; # replace NULL with a proper value
#my $random_meme_min_rating = undef; # replace NULL with a proper value
#my $random_meme_result = $api->random_meme(keywords => $random_meme_keywords, keywords_in_image => $random_meme_keywords_in_image, media_type => $random_meme_media_type, number => $random_meme_number, min_rating => $random_meme_min_rating);

#
# search_memes test
#
# uncomment below and update the test
#my $search_memes_keywords = undef; # replace NULL with a proper value
#my $search_memes_keywords_in_image = undef; # replace NULL with a proper value
#my $search_memes_media_type = undef; # replace NULL with a proper value
#my $search_memes_number = undef; # replace NULL with a proper value
#my $search_memes_min_rating = undef; # replace NULL with a proper value
#my $search_memes_offset = undef; # replace NULL with a proper value
#my $search_memes_result = $api->search_memes(keywords => $search_memes_keywords, keywords_in_image => $search_memes_keywords_in_image, media_type => $search_memes_media_type, number => $search_memes_number, min_rating => $search_memes_min_rating, offset => $search_memes_offset);

#
# upvote_meme test
#
# uncomment below and update the test
#my $upvote_meme_id = undef; # replace NULL with a proper value
#my $upvote_meme_result = $api->upvote_meme(id => $upvote_meme_id);

