/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AnalyzeJoke200Response from './model/AnalyzeJoke200Response';
import GenerateNonsenseWord200Response from './model/GenerateNonsenseWord200Response';
import Praise200Response from './model/Praise200Response';
import RandomJoke200Response from './model/RandomJoke200Response';
import RandomMeme200Response from './model/RandomMeme200Response';
import RateWord200Response from './model/RateWord200Response';
import SearchGifs200Response from './model/SearchGifs200Response';
import SearchGifs200ResponseImagesInner from './model/SearchGifs200ResponseImagesInner';
import SearchJokes200Response from './model/SearchJokes200Response';
import SearchJokes200ResponseJokesInner from './model/SearchJokes200ResponseJokesInner';
import SearchMemes200Response from './model/SearchMemes200Response';
import SearchMemes200ResponseMemesInner from './model/SearchMemes200ResponseMemesInner';
import SubmitJoke200Response from './model/SubmitJoke200Response';
import JokesApi from './api/JokesApi';
import MemesApi from './api/MemesApi';
import OtherApi from './api/OtherApi';


/**
* Awesome Humor API..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var HumorApi = require('index'); // See note below*.
* var xxxSvc = new HumorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new HumorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new HumorApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new HumorApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AnalyzeJoke200Response model constructor.
     * @property {module:model/AnalyzeJoke200Response}
     */
    AnalyzeJoke200Response,

    /**
     * The GenerateNonsenseWord200Response model constructor.
     * @property {module:model/GenerateNonsenseWord200Response}
     */
    GenerateNonsenseWord200Response,

    /**
     * The Praise200Response model constructor.
     * @property {module:model/Praise200Response}
     */
    Praise200Response,

    /**
     * The RandomJoke200Response model constructor.
     * @property {module:model/RandomJoke200Response}
     */
    RandomJoke200Response,

    /**
     * The RandomMeme200Response model constructor.
     * @property {module:model/RandomMeme200Response}
     */
    RandomMeme200Response,

    /**
     * The RateWord200Response model constructor.
     * @property {module:model/RateWord200Response}
     */
    RateWord200Response,

    /**
     * The SearchGifs200Response model constructor.
     * @property {module:model/SearchGifs200Response}
     */
    SearchGifs200Response,

    /**
     * The SearchGifs200ResponseImagesInner model constructor.
     * @property {module:model/SearchGifs200ResponseImagesInner}
     */
    SearchGifs200ResponseImagesInner,

    /**
     * The SearchJokes200Response model constructor.
     * @property {module:model/SearchJokes200Response}
     */
    SearchJokes200Response,

    /**
     * The SearchJokes200ResponseJokesInner model constructor.
     * @property {module:model/SearchJokes200ResponseJokesInner}
     */
    SearchJokes200ResponseJokesInner,

    /**
     * The SearchMemes200Response model constructor.
     * @property {module:model/SearchMemes200Response}
     */
    SearchMemes200Response,

    /**
     * The SearchMemes200ResponseMemesInner model constructor.
     * @property {module:model/SearchMemes200ResponseMemesInner}
     */
    SearchMemes200ResponseMemesInner,

    /**
     * The SubmitJoke200Response model constructor.
     * @property {module:model/SubmitJoke200Response}
     */
    SubmitJoke200Response,

    /**
    * The JokesApi service constructor.
    * @property {module:api/JokesApi}
    */
    JokesApi,

    /**
    * The MemesApi service constructor.
    * @property {module:api/MemesApi}
    */
    MemesApi,

    /**
    * The OtherApi service constructor.
    * @property {module:api/OtherApi}
    */
    OtherApi
};
