/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200_4.h
 *
 * 
 */

#ifndef OAIInline_response_200_4_H
#define OAIInline_response_200_4_H

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIInline_response_200_4: public OAIObject {
public:
    OAIInline_response_200_4();
    OAIInline_response_200_4(QString json);
    ~OAIInline_response_200_4() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    qint32 getId() const;
    void setId(const qint32 &id);

    
    QString getJoke() const;
    void setJoke(const QString &joke);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    qint32 id;
    bool m_id_isSet;
    bool m_id_isValid;
    
    QString joke;
    bool m_joke_isSet;
    bool m_joke_isValid;
    
    };

}

#endif // OAIInline_response_200_4_H
