/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIInline_response_200.h
 *
 * 
 */

#ifndef OAIInline_response_200_H
#define OAIInline_response_200_H

#include <QJsonObject>


#include "com.humorapi.client.model\OAIObject.h"
#include <QList>

#include "OAIObject.h"
#include "OAIEnum.h"

namespace OpenAPI {

class OAIInline_response_200: public OAIObject {
public:
    OAIInline_response_200();
    OAIInline_response_200(QString json);
    ~OAIInline_response_200() override;

    QString asJson () const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    
    QList<OAIObject> getJokes() const;
    void setJokes(const QList<OAIObject> &jokes);

    
    
    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void init();
    
    QList<OAIObject> jokes;
    bool m_jokes_isSet;
    bool m_jokes_isValid;
    
    };

}

#endif // OAIInline_response_200_H
