package = "humorapi"
version = "1.0.8"
source = {
	url = "https://github.com/ddsky/humor-api-clients/tree/main/lua/.git"
}

description = {
	summary = "API client generated by OpenAPI Generator",
	detailed = [[
Awesome Humor API.]],
	homepage = "https://openapi-generator.tech",
	license = "Unlicense",
	maintainer = "OpenAPI Generator contributors",
}

dependencies = {
	"lua >= 5.2",
	"http",
	"dkjson",
	"basexx"
}

build = {
	type = "builtin",
	modules = {
		["humorapi.api.jokes_api"] = "humorapi/api/jokes_api.lua";
		["humorapi.api.memes_api"] = "humorapi/api/memes_api.lua";
		["humorapi.api.other_api"] = "humorapi/api/other_api.lua";
		["humorapi.model.analyze_joke_200_response"] = "humorapi/model/analyze_joke_200_response.lua";
		["humorapi.model.generate_nonsense_word_200_response"] = "humorapi/model/generate_nonsense_word_200_response.lua";
		["humorapi.model.praise_200_response"] = "humorapi/model/praise_200_response.lua";
		["humorapi.model.random_joke_200_response"] = "humorapi/model/random_joke_200_response.lua";
		["humorapi.model.random_meme_200_response"] = "humorapi/model/random_meme_200_response.lua";
		["humorapi.model.rate_word_200_response"] = "humorapi/model/rate_word_200_response.lua";
		["humorapi.model.search_gifs_200_response"] = "humorapi/model/search_gifs_200_response.lua";
		["humorapi.model.search_gifs_200_response_images_inner"] = "humorapi/model/search_gifs_200_response_images_inner.lua";
		["humorapi.model.search_jokes_200_response"] = "humorapi/model/search_jokes_200_response.lua";
		["humorapi.model.search_jokes_200_response_jokes_inner"] = "humorapi/model/search_jokes_200_response_jokes_inner.lua";
		["humorapi.model.search_memes_200_response"] = "humorapi/model/search_memes_200_response.lua";
		["humorapi.model.search_memes_200_response_memes_inner"] = "humorapi/model/search_memes_200_response_memes_inner.lua";
		["humorapi.model.submit_joke_200_response"] = "humorapi/model/submit_joke_200_response.lua";
	}
}
