/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GenerateNonsenseWord200Response from '../model/GenerateNonsenseWord200Response';
import Praise200Response from '../model/Praise200Response';
import RateWord200Response from '../model/RateWord200Response';
import SearchGifs200Response from '../model/SearchGifs200Response';

/**
* Other service.
* @module api/OtherApi
* @version 1.0
*/
export default class OtherApi {

    /**
    * Constructs a new OtherApi. 
    * @alias module:api/OtherApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the generateNonsenseWord operation.
     * @callback module:api/OtherApi~generateNonsenseWordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenerateNonsenseWord200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Generate Nonsense Word
     * Generate a nonsense word. See https://humorapi.com/docs/#Generate-Nonsense-Word for more.
     * @param {module:api/OtherApi~generateNonsenseWordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GenerateNonsenseWord200Response}
     */
    generateNonsenseWord(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GenerateNonsenseWord200Response;
      return this.apiClient.callApi(
        '/words/nonsense/random', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the insult operation.
     * @callback module:api/OtherApi~insultCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Praise200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Insult
     * Insult somebody for doing something. See https://humorapi.com/docs/#Insult for more.
     * @param {String} name The person's name.
     * @param {String} reason The reason for the praise/insult.
     * @param {module:api/OtherApi~insultCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Praise200Response}
     */
    insult(name, reason, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling insult");
      }
      // verify the required parameter 'reason' is set
      if (reason === undefined || reason === null) {
        throw new Error("Missing the required parameter 'reason' when calling insult");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'reason': reason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Praise200Response;
      return this.apiClient.callApi(
        '/insult', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the praise operation.
     * @callback module:api/OtherApi~praiseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Praise200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Praise
     * Praise somebody for doing something. See https://humorapi.com/docs/#Praise for more.
     * @param {String} name The person's name.
     * @param {String} reason The reason for the praise/insult.
     * @param {module:api/OtherApi~praiseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Praise200Response}
     */
    praise(name, reason, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling praise");
      }
      // verify the required parameter 'reason' is set
      if (reason === undefined || reason === null) {
        throw new Error("Missing the required parameter 'reason' when calling praise");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'reason': reason
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Praise200Response;
      return this.apiClient.callApi(
        '/praise', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the rateWord operation.
     * @callback module:api/OtherApi~rateWordCallback
     * @param {String} error Error message, if any.
     * @param {module:model/RateWord200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Rate Word
     * Rate the funniness of a word. See https://humorapi.com/docs/#Rate-Word for more.
     * @param {String} word The word to be rated.
     * @param {module:api/OtherApi~rateWordCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/RateWord200Response}
     */
    rateWord(word, callback) {
      let postBody = null;
      // verify the required parameter 'word' is set
      if (word === undefined || word === null) {
        throw new Error("Missing the required parameter 'word' when calling rateWord");
      }

      let pathParams = {
      };
      let queryParams = {
        'word': word
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = RateWord200Response;
      return this.apiClient.callApi(
        '/words/rate', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the searchGifs operation.
     * @callback module:api/OtherApi~searchGifsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SearchGifs200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search Gifs
     * Search for gifs. See https://humorapi.com/docs/#Search-Gifs for more.
     * @param {String} query A search query.
     * @param {Object} opts Optional parameters
     * @param {Number} [number] The number of results to retrieve between 1 and 10.
     * @param {module:api/OtherApi~searchGifsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SearchGifs200Response}
     */
    searchGifs(query, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'query' is set
      if (query === undefined || query === null) {
        throw new Error("Missing the required parameter 'query' when calling searchGifs");
      }

      let pathParams = {
      };
      let queryParams = {
        'query': query,
        'number': opts['number']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SearchGifs200Response;
      return this.apiClient.callApi(
        '/gif/search', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
