# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule com.humorapi.client.Model.InlineResponse200 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"jokes"
  ]

  @type t :: %__MODULE__{
    :"jokes" => [Map]
  }
end

defimpl Poison.Decoder, for: com.humorapi.client.Model.InlineResponse200 do
  def decode(value, _options) do
    value
  end
end

