/*
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.humorapi;

import com.humorapi.client.ApiException;
import com.humorapi.client.model.GenerateNonsenseWord200Response;
import com.humorapi.client.model.Praise200Response;
import com.humorapi.client.model.RateWord200Response;
import com.humorapi.client.model.SearchGifs200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OtherApi
 */
@Disabled
public class OtherApiTest {

    private final OtherApi api = new OtherApi();

    /**
     * Generate Nonsense Word
     *
     * Generate a nonsense word. See https://humorapi.com/docs/#Generate-Nonsense-Word for more.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void generateNonsenseWordTest() throws ApiException {
        GenerateNonsenseWord200Response response = api.generateNonsenseWord();
        // TODO: test validations
    }

    /**
     * Insult
     *
     * Insult somebody for doing something. See https://humorapi.com/docs/#Insult for more.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void insultTest() throws ApiException {
        String name = null;
        String reason = null;
        Praise200Response response = api.insult(name, reason);
        // TODO: test validations
    }

    /**
     * Praise
     *
     * Praise somebody for doing something. See https://humorapi.com/docs/#Praise for more.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void praiseTest() throws ApiException {
        String name = null;
        String reason = null;
        Praise200Response response = api.praise(name, reason);
        // TODO: test validations
    }

    /**
     * Rate Word
     *
     * Rate the funniness of a word. See https://humorapi.com/docs/#Rate-Word for more.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void rateWordTest() throws ApiException {
        String word = null;
        RateWord200Response response = api.rateWord(word);
        // TODO: test validations
    }

    /**
     * Search Gifs
     *
     * Search for gifs. See https://humorapi.com/docs/#Search-Gifs for more.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void searchGifsTest() throws ApiException {
        String query = null;
        Integer number = null;
        SearchGifs200Response response = api.searchGifs(query, number);
        // TODO: test validations
    }

}
