/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchJokes200ResponseJokesInner } from './searchJokes200ResponseJokesInner';


/**
 * 
 */
export interface SearchJokes200Response { 
    jokes: Set<SearchJokes200ResponseJokesInner>;
}

