/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SearchMemes200ResponseMemesInner } from './searchMemes200ResponseMemesInner';


/**
 * 
 */
export interface SearchMemes200Response { 
    memes: Set<SearchMemes200ResponseMemesInner>;
}

