/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2006 model module.
 * @module com.humorapi.client/com.humorapi.client.model/InlineResponse2006
 * @version 1.0
 */
class InlineResponse2006 {
    /**
     * Constructs a new <code>InlineResponse2006</code>.
     * @alias module:com.humorapi.client/com.humorapi.client.model/InlineResponse2006
     * @param rating {Number} 
     */
    constructor(rating) { 
        
        InlineResponse2006.initialize(this, rating);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, rating) { 
        obj['rating'] = rating;
    }

    /**
     * Constructs a <code>InlineResponse2006</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.humorapi.client/com.humorapi.client.model/InlineResponse2006} obj Optional instance to populate.
     * @return {module:com.humorapi.client/com.humorapi.client.model/InlineResponse2006} The populated <code>InlineResponse2006</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2006();

            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} rating
 */
InlineResponse2006.prototype['rating'] = undefined;






export default InlineResponse2006;

