/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2004 model module.
 * @module com.humorapi.client/com.humorapi.client.model/InlineResponse2004
 * @version 1.0
 */
class InlineResponse2004 {
    /**
     * Constructs a new <code>InlineResponse2004</code>.
     * @alias module:com.humorapi.client/com.humorapi.client.model/InlineResponse2004
     * @param id {Number} 
     * @param joke {String} 
     */
    constructor(id, joke) { 
        
        InlineResponse2004.initialize(this, id, joke);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, joke) { 
        obj['id'] = id;
        obj['joke'] = joke;
    }

    /**
     * Constructs a <code>InlineResponse2004</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:com.humorapi.client/com.humorapi.client.model/InlineResponse2004} obj Optional instance to populate.
     * @return {module:com.humorapi.client/com.humorapi.client.model/InlineResponse2004} The populated <code>InlineResponse2004</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2004();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('joke')) {
                obj['joke'] = ApiClient.convertToType(data['joke'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
InlineResponse2004.prototype['id'] = undefined;

/**
 * @member {String} joke
 */
InlineResponse2004.prototype['joke'] = undefined;






export default InlineResponse2004;

