/**
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "OAISearch_jokes_200_response_jokes_inner.h"

#include <QDebug>
#include <QJsonArray>
#include <QJsonDocument>
#include <QObject>

#include "OAIHelpers.h"

namespace OpenAPI {

OAISearch_jokes_200_response_jokes_inner::OAISearch_jokes_200_response_jokes_inner(QString json) {
    this->initializeModel();
    this->fromJson(json);
}

OAISearch_jokes_200_response_jokes_inner::OAISearch_jokes_200_response_jokes_inner() {
    this->initializeModel();
}

OAISearch_jokes_200_response_jokes_inner::~OAISearch_jokes_200_response_jokes_inner() {}

void OAISearch_jokes_200_response_jokes_inner::initializeModel() {

    m_id_isSet = false;
    m_id_isValid = false;

    m_joke_isSet = false;
    m_joke_isValid = false;
}

void OAISearch_jokes_200_response_jokes_inner::fromJson(QString jsonString) {
    QByteArray array(jsonString.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
}

void OAISearch_jokes_200_response_jokes_inner::fromJsonObject(QJsonObject json) {

    m_id_isValid = ::OpenAPI::fromJsonValue(m_id, json[QString("id")]);
    m_id_isSet = !json[QString("id")].isNull() && m_id_isValid;

    m_joke_isValid = ::OpenAPI::fromJsonValue(m_joke, json[QString("joke")]);
    m_joke_isSet = !json[QString("joke")].isNull() && m_joke_isValid;
}

QString OAISearch_jokes_200_response_jokes_inner::asJson() const {
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject OAISearch_jokes_200_response_jokes_inner::asJsonObject() const {
    QJsonObject obj;
    if (m_id_isSet) {
        obj.insert(QString("id"), ::OpenAPI::toJsonValue(m_id));
    }
    if (m_joke_isSet) {
        obj.insert(QString("joke"), ::OpenAPI::toJsonValue(m_joke));
    }
    return obj;
}

qint32 OAISearch_jokes_200_response_jokes_inner::getId() const {
    return m_id;
}
void OAISearch_jokes_200_response_jokes_inner::setId(const qint32 &id) {
    m_id = id;
    m_id_isSet = true;
}

bool OAISearch_jokes_200_response_jokes_inner::is_id_Set() const{
    return m_id_isSet;
}

bool OAISearch_jokes_200_response_jokes_inner::is_id_Valid() const{
    return m_id_isValid;
}

QString OAISearch_jokes_200_response_jokes_inner::getJoke() const {
    return m_joke;
}
void OAISearch_jokes_200_response_jokes_inner::setJoke(const QString &joke) {
    m_joke = joke;
    m_joke_isSet = true;
}

bool OAISearch_jokes_200_response_jokes_inner::is_joke_Set() const{
    return m_joke_isSet;
}

bool OAISearch_jokes_200_response_jokes_inner::is_joke_Valid() const{
    return m_joke_isValid;
}

bool OAISearch_jokes_200_response_jokes_inner::isSet() const {
    bool isObjectUpdated = false;
    do {
        if (m_id_isSet) {
            isObjectUpdated = true;
            break;
        }

        if (m_joke_isSet) {
            isObjectUpdated = true;
            break;
        }
    } while (false);
    return isObjectUpdated;
}

bool OAISearch_jokes_200_response_jokes_inner::isValid() const {
    // only required properties are required for the object to be considered valid
    return m_id_isValid && m_joke_isValid && true;
}

} // namespace OpenAPI
