# coding: utf-8

# flake8: noqa

"""
    Humor API

    Awesome Humor API.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: mail@humorapi.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from com.humorapi.jokes_api import JokesApi
from com.humorapi.memes_api import MemesApi
from com.humorapi.other_api import OtherApi

# import ApiClient
from humorapi.api_client import ApiClient
from humorapi.configuration import Configuration
from humorapi.exceptions import OpenApiException
from humorapi.exceptions import ApiTypeError
from humorapi.exceptions import ApiValueError
from humorapi.exceptions import ApiKeyError
from humorapi.exceptions import ApiException
# import models into sdk package
from humorapi.com.humorapi.client.model.inline_response200 import InlineResponse200
from humorapi.com.humorapi.client.model.inline_response2001 import InlineResponse2001
from humorapi.com.humorapi.client.model.inline_response2002 import InlineResponse2002
from humorapi.com.humorapi.client.model.inline_response2003 import InlineResponse2003
from humorapi.com.humorapi.client.model.inline_response2004 import InlineResponse2004
from humorapi.com.humorapi.client.model.inline_response2005 import InlineResponse2005
from humorapi.com.humorapi.client.model.inline_response2006 import InlineResponse2006
from humorapi.com.humorapi.client.model.inline_response2007 import InlineResponse2007
from humorapi.com.humorapi.client.model.inline_response2008 import InlineResponse2008
from humorapi.com.humorapi.client.model.inline_response2009 import InlineResponse2009

