/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2002 {
    #[serde(rename = "memes")]
    pub memes: Vec<Value>,
}

impl InlineResponse2002 {
    pub fn new(memes: Vec<Value>) -> InlineResponse2002 {
        InlineResponse2002 {
            memes: memes,
        }
    }
}
