/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchJokes200ResponseJokesInner {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "joke")]
    pub joke: String,
}

impl SearchJokes200ResponseJokesInner {
    pub fn new(id: i32, joke: String) -> SearchJokes200ResponseJokesInner {
        SearchJokes200ResponseJokesInner {
            id,
            joke,
        }
    }
}


