/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 * Generated by: https://openapi-generator.tech
 */

/// SearchMemes200Response : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SearchMemes200Response {
    #[serde(rename = "memes")]
    pub memes: Vec<crate::models::SearchMemes200ResponseMemesInner>,
}

impl SearchMemes200Response {
    /// 
    pub fn new(memes: Vec<crate::models::SearchMemes200ResponseMemesInner>) -> SearchMemes200Response {
        SearchMemes200Response {
            memes,
        }
    }
}


