/**
 * Humor API
 * Awesome Humor API.
 *
 * OpenAPI spec version: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SearchGifs200ResponseImagesInner } from '../models/SearchGifs200ResponseImagesInner';
import { HttpFile } from '../http/http';

/**
* 
*/
export class SearchGifs200Response {
    'images': Set<SearchGifs200ResponseImagesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "images",
            "baseName": "images",
            "type": "Set<SearchGifs200ResponseImagesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchGifs200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

