/**
 * Humor API
 * Awesome Humor API.
 *
 * OpenAPI spec version: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SearchGifs200ResponseImagesInner {
    'url': string;
    'width': number;
    'height': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "width",
            "baseName": "width",
            "type": "number",
            "format": ""
        },
        {
            "name": "height",
            "baseName": "height",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchGifs200ResponseImagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

