/*
 * Humor API
 * Awesome Humor API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mail@humorapi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.humorapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GenerateNonsenseWord200Response
 */
public class GenerateNonsenseWord200ResponseTest {
    private final GenerateNonsenseWord200Response model = new GenerateNonsenseWord200Response();

    /**
     * Model tests for GenerateNonsenseWord200Response
     */
    @Test
    public void testGenerateNonsenseWord200Response() {
        // TODO: test GenerateNonsenseWord200Response
    }

    /**
     * Test the property 'word'
     */
    @Test
    public void wordTest() {
        // TODO: test word
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

}
