/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * API version: 1.0
 * Contact: mail@humorapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package humorapi

type InlineResponse2003 struct {
	Id int32 `json:"id"`
	Url string `json:"url"`
	Type string `json:"type"`
}
