/*
 * Humor API
 *
 * Awesome Humor API.
 *
 * API version: 1.0
 * Contact: mail@humorapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package humorapi

type InlineResponse2008 struct {
	Message string `json:"message"`
}
