#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Humor API
* Awesome Humor API.
*
* The version of the OpenAPI document: 1.0
* Contact: mail@humorapi.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIInlineResponse2001
@end

@interface OAIInlineResponse2001 : OAIObject


@property(nonatomic) NSArray<NSObject*>* images;

@end
